# Generated by Django 5.0.2 on 2024-09-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
